[2023-06-18T14:59:53.474+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2023-06-17T00:00:00+00:00 [queued]>
[2023-06-18T14:59:53.508+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2023-06-17T00:00:00+00:00 [queued]>
[2023-06-18T14:59:53.509+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-18T14:59:53.510+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-06-18T14:59:53.514+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-18T14:59:53.619+0000] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): download_dataset_task> on 2023-06-17 00:00:00+00:00
[2023-06-18T14:59:53.684+0000] {standard_task_runner.py:55} INFO - Started process 2041 to run task
[2023-06-18T14:59:53.694+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'scheduled__2023-06-17T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dags_new/dag_ingestion_kaggle.py', '--cfg-path', '/tmp/tmp1c3hkstw']
[2023-06-18T14:59:53.698+0000] {standard_task_runner.py:83} INFO - Job 12: Subtask download_dataset_task
[2023-06-18T14:59:54.011+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2023-06-17T00:00:00+00:00 [running]> on host d0aad92f0cfd
[2023-06-18T14:59:54.240+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-17T00:00:00+00:00
[2023-06-18T14:59:54.245+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-18T14:59:54.251+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            cd /opt/*** &&\n            cd data-science-salaries-2023 &&\n            rm -f data-science-salaries-2023.zip &&\n            rm ds_salaries.csv &&\n            kaggle datasets download -d arnabchaki/data-science-salaries-2023 --force && \n            unzip data-science-salaries-2023.zip && \n            rm data-science-salaries-2023.zip\n            ']
[2023-06-18T14:59:54.297+0000] {subprocess.py:86} INFO - Output:
[2023-06-18T14:59:54.372+0000] {subprocess.py:93} INFO - /bin/bash: line 3: cd: data-science-salaries-2023: No such file or directory
[2023-06-18T14:59:54.378+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-06-18T14:59:54.425+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-06-18T14:59:54.452+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20230617T000000, start_date=20230618T145953, end_date=20230618T145954
[2023-06-18T14:59:54.496+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 12 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 1.; 2041)
[2023-06-18T14:59:54.526+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-18T14:59:54.603+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
