[2023-06-18T17:02:34.090+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_kaggle_zip_bq.create_tables manual__2023-06-18T16:55:36.332282+00:00 [queued]>
[2023-06-18T17:02:34.109+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_kaggle_zip_bq.create_tables manual__2023-06-18T16:55:36.332282+00:00 [queued]>
[2023-06-18T17:02:34.110+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-06-18T17:02:34.111+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-06-18T17:02:34.112+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-06-18T17:02:34.139+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): create_tables> on 2023-06-18 16:55:36.332282+00:00
[2023-06-18T17:02:34.151+0000] {standard_task_runner.py:55} INFO - Started process 8733 to run task
[2023-06-18T17:02:34.155+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_kaggle_zip_bq', 'create_tables', 'manual__2023-06-18T16:55:36.332282+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_kaggle_zip_bq.py', '--cfg-path', '/tmp/tmpsivn4tz9']
[2023-06-18T17:02:34.157+0000] {standard_task_runner.py:83} INFO - Job 41: Subtask create_tables
[2023-06-18T17:02:34.249+0000] {task_command.py:388} INFO - Running <TaskInstance: data_ingestion_kaggle_zip_bq.create_tables manual__2023-06-18T16:55:36.332282+00:00 [running]> on host d0aad92f0cfd
[2023-06-18T17:02:34.350+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_kaggle_zip_bq
AIRFLOW_CTX_TASK_ID=create_tables
AIRFLOW_CTX_EXECUTION_DATE=2023-06-18T16:55:36.332282+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-18T16:55:36.332282+00:00
[2023-06-18T17:02:36.393+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_kaggle_zip_bq.py", line 67, in create_multiple_tables
    table = client.create_table(table)  # Make an API request.
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 755, in create_table
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/prime-byway-387902/datasets/project1_data/tables?prettyPrint=false: Invalid table ID "/opt/airflow/corona-virus-report/".
[2023-06-18T17:02:36.440+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_kaggle_zip_bq, task_id=create_tables, execution_date=20230618T165536, start_date=20230618T170234, end_date=20230618T170236
[2023-06-18T17:02:36.465+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 41 for task create_tables (400 POST https://bigquery.googleapis.com/bigquery/v2/projects/prime-byway-387902/datasets/project1_data/tables?prettyPrint=false: Invalid table ID "/opt/airflow/corona-virus-report/".; 8733)
[2023-06-18T17:02:36.499+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-18T17:02:36.530+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
